=== CaroFlores/SitioInstrumentosMTI/entrega/1. representacion de la informacion/producto.dtd
<!ELEMENT producto (codigo,nombre,precio,descripcion,marca,modelo,origen)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT origen (#PCDATA)>

=== CaroFlores/SitioInstrumentosMTI/entrega/1. representacion de la informacion/producto.xml
<?xml version="1.0"?>
<!DOCTYPE producto SYSTEM "producto.dtd">
<producto>
  <codigo>737383</codigo>
  <nombre>Guitarra</nombre>
  <precio>200000</precio>
  <descripcion>Sin informacion</descripcion>
  <marca>Yamaha</marca>
  <modelo>C-41</modelo>
  <origen>Chile</origen>
</producto>
